{ pkgs, ... }:
{
  home.packages = with pkgs; [
    wget
    curl
    jq
    silver-searcher
    swww
    xfce.thunar
    hyprpolkitagent
    hypridle
    hyprlock
    obsidian
    dunst
    wl-clipboard
    networkmanagerapplet
    wl-color-picker
    playerctl
    brightnessctl
    pavucontrol
    wev
    nwg-look
    nwg-displays
    catppuccin-gtk
    catppuccin-cursors.mochaDark
    rofi-power-menu
    starship
    qimgv
    typst
    kdePackages.okular
    font-awesome
    gimp
  ];
}
